server:
  port: 9090
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/UserManagementApp
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
